name: apiverve_htmltotext
description: HTML to Text is a simple tool for converting HTML to text. It returns the text extracted from the HTML.
version: 1.1.14
homepage: https://htmltotext.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/htmltotext-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
